import { Car, NavLink, PriceRange } from "./types";

export const publicNavLinks: NavLink[] = [
  { name: "Service", href: "#services" },
  { name: "Cars", href: "/cars" },
  { name: "Pricing", href: "#pricing" },
  { name: "About", href: "#about" },
];

export const authNavLinks: NavLink[] = [
  { name: "Dashboard", href: "/dashboard" },
  { name: "Browse Cars", href: "/cars" },
];

export const carTypes = ["All", "Sedan", "SUV", "Sports"] as const;
export const fuelTypes = [
  "All",
  "Petrol",
  "Diesel",
  "Electric",
  "Hybrid",
] as const;
export const transmissions = ["All", "Automatic", "Manual"] as const;

export const priceRanges: PriceRange[] = [
  { label: "All", min: 0, max: Infinity },
  { label: "Under $100", min: 0, max: 100 },
  { label: "$100 - $200", min: 100, max: 200 },
  { label: "$200 - $500", min: 200, max: 500 },
  { label: "$500+", min: 500, max: Infinity },
];

export const fallbackCars: Car[] = [
  {
    id: "1",
    make: "Audi",
    model: "A4",
    year: 2024,
    type: "Sedan",
    transmission: "Automatic",
    fuelType: "Petrol",
    seats: 5,
    pricePerDay: "89.00",
    imageUrl: "/cars/hero-car.png",
    description: "Luxury sedan with premium features",
    available: true,
    featured: true,
  },
  {
    id: "2",
    make: "BMW",
    model: "X5",
    year: 2024,
    type: "SUV",
    transmission: "Automatic",
    fuelType: "Diesel",
    seats: 7,
    pricePerDay: "129.00",
    imageUrl: "/cars/hero-car.png",
    description: "Spacious luxury SUV for family trips",
    available: true,
    featured: true,
  },
  {
    id: "3",
    make: "Mercedes",
    model: "C-Class",
    year: 2024,
    type: "Sedan",
    transmission: "Automatic",
    fuelType: "Hybrid",
    seats: 5,
    pricePerDay: "99.00",
    imageUrl: "/cars/hero-car.png",
    description: "Elegant and fuel-efficient",
    available: true,
    featured: false,
  },
  {
    id: "4",
    make: "Porsche",
    model: "911",
    year: 2024,
    type: "Sports",
    transmission: "Manual",
    fuelType: "Petrol",
    seats: 2,
    pricePerDay: "249.00",
    imageUrl: "/cars/hero-car.png",
    description: "Ultimate driving experience",
    available: true,
    featured: true,
  },
  {
    id: "5",
    make: "Tesla",
    model: "Model 3",
    year: 2024,
    type: "Sedan",
    transmission: "Automatic",
    fuelType: "Electric",
    seats: 5,
    pricePerDay: "109.00",
    imageUrl: "/cars/hero-car.png",
    description: "Zero emissions, maximum performance",
    available: true,
    featured: false,
  },
  {
    id: "6",
    make: "Range Rover",
    model: "Sport",
    year: 2024,
    type: "SUV",
    transmission: "Automatic",
    fuelType: "Diesel",
    seats: 5,
    pricePerDay: "179.00",
    imageUrl: "/cars/hero-car.png",
    description: "Luxury meets adventure",
    available: true,
    featured: true,
  },
];

export const extendedFallbackCars: Car[] = [
  ...fallbackCars,
  {
    id: "7",
    make: "Ferrari",
    model: "F8 Tributo",
    year: 2024,
    type: "Sports",
    transmission: "Automatic",
    fuelType: "Petrol",
    seats: 2,
    pricePerDay: "599.00",
    imageUrl: "/cars/hero-car.png",
    description: "Italian supercar with breathtaking performance",
    available: true,
    featured: true,
  },
  {
    id: "8",
    make: "Lamborghini",
    model: "Huracán",
    year: 2024,
    type: "Sports",
    transmission: "Automatic",
    fuelType: "Petrol",
    seats: 2,
    pricePerDay: "649.00",
    imageUrl: "/cars/hero-car.png",
    description: "Raging bull with V10 power",
    available: true,
    featured: true,
  },
  {
    id: "9",
    make: "Toyota",
    model: "Camry",
    year: 2024,
    type: "Sedan",
    transmission: "Automatic",
    fuelType: "Hybrid",
    seats: 5,
    pricePerDay: "59.00",
    imageUrl: "/cars/hero-car.png",
    description: "Reliable and fuel-efficient family sedan",
    available: true,
    featured: false,
  },
  {
    id: "10",
    make: "Ford",
    model: "Mustang",
    year: 2024,
    type: "Sports",
    transmission: "Manual",
    fuelType: "Petrol",
    seats: 4,
    pricePerDay: "149.00",
    imageUrl: "/cars/hero-car.png",
    description: "American muscle with iconic styling",
    available: true,
    featured: true,
  },
  {
    id: "11",
    make: "Chevrolet",
    model: "Tahoe",
    year: 2024,
    type: "SUV",
    transmission: "Automatic",
    fuelType: "Petrol",
    seats: 8,
    pricePerDay: "139.00",
    imageUrl: "/cars/hero-car.png",
    description: "Full-size SUV with maximum space",
    available: true,
    featured: false,
  },
  {
    id: "12",
    make: "Rivian",
    model: "R1S",
    year: 2024,
    type: "SUV",
    transmission: "Automatic",
    fuelType: "Electric",
    seats: 7,
    pricePerDay: "189.00",
    imageUrl: "/cars/hero-car.png",
    description: "Electric adventure vehicle with off-road capability",
    available: true,
    featured: true,
  },
];

export const bookingStatusColors: Record<string, string> = {
  confirmed: "bg-green-100 text-green-700",
  pending: "bg-yellow-100 text-yellow-700",
  completed: "bg-blue-100 text-blue-700",
  cancelled: "bg-red-100 text-red-700",
};

export function getBookingStatusColor(status: string): string {
  return bookingStatusColors[status] || "bg-gray-100 text-gray-700";
}
